// Lists the direct dependencies of every workspace with their licences (for docs/DEPENDENCIES.md) and scans the whole
// installed tree for licences that are not MIT, Apache-2.0, BSD, ISC or similar permissive ones.
//
//   node scripts/licenses.mjs            print the tables as Markdown
//   node scripts/licenses.mjs --write    write docs/DEPENDENCIES.md (keeps the hand-written text above the tables)
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = new URL('../', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const read = (path) => JSON.parse(readFileSync(path, 'utf8'));

function licenseOf(pkg) {
  const value = pkg.license ?? (Array.isArray(pkg.licenses) ? pkg.licenses.map((entry) => entry.type).join(' OR ') : pkg.licenses?.type);
  return typeof value === 'object' && value !== null ? value.type : (value ?? 'UNKNOWN');
}

function find(name, from) {
  const candidates = [join(from, 'node_modules', name, 'package.json'), join(root, 'node_modules', name, 'package.json')];
  return candidates.find((path) => existsSync(path));
}

const workspaces = [
  ['root (tooling)', root],
  ['@mcprep/core', join(root, 'packages/core')],
  ['@mcprep/cli', join(root, 'packages/cli')],
  ['@mcprep/mcp', join(root, 'packages/mcp')],
  ['@mcprep/desktop', join(root, 'apps/desktop')],
];

const permissive = /^(MIT|ISC|0BSD|Apache-2\.0|BSD-2-Clause|BSD-3-Clause|BlueOak-1\.0\.0|Python-2\.0|CC0-1\.0|Unlicense|MIT-0|Zlib|CC-BY-4\.0|OFL-1\.1)$/;

const rows = [];
for (const [label, dir] of workspaces) {
  const pkg = read(join(dir, 'package.json'));
  for (const [kind, deps] of [['runtime', pkg.dependencies], ['development', pkg.devDependencies]]) {
    for (const name of Object.keys(deps ?? {})) {
      if (name.startsWith('@mcprep/')) continue;
      const path = find(name, dir);
      if (!path) continue;
      const installed = read(path);
      rows.push({ workspace: label, kind, name, version: installed.version, license: licenseOf(installed) });
    }
  }
}

// The whole installed tree.
const tree = new Map();
function scan(nodeModules) {
  if (!existsSync(nodeModules)) return;
  for (const entry of readdirSync(nodeModules, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    const full = join(nodeModules, entry.name);
    const names = entry.name.startsWith('@') ? readdirSync(full).map((sub) => [`${entry.name}/${sub}`, join(full, sub)]) : [[entry.name, full]];
    for (const [name, dir] of names) {
      const manifest = join(dir, 'package.json');
      if (!existsSync(manifest)) continue;
      try {
        const pkg = read(manifest);
        if (!name.startsWith('@mcprep/')) tree.set(`${name}@${pkg.version}`, licenseOf(pkg));
      } catch {
        // ignore unreadable manifests
      }
      scan(join(dir, 'node_modules'));
    }
  }
}
scan(join(root, 'node_modules'));
for (const [, dir] of workspaces.slice(1)) scan(join(dir, 'node_modules'));

const unusual = [...tree.entries()].filter(([name, license]) => !name.startsWith('@mcprep/') && ![...String(license).split(/\s+(?:OR|AND)\s+|\s*[()]\s*/)].some((part) => permissive.test(part.trim()))).sort();
const counts = new Map();
for (const license of tree.values()) counts.set(license, (counts.get(license) ?? 0) + 1);

const table = (list) => ['| Package | Version | Licence |', '| --- | --- | --- |', ...list.map((row) => `| \`${row.name}\` | ${row.version} | ${row.license} |`)].join('\n');
const output = [
  ...workspaces.map(([label]) => {
    const mine = rows.filter((row) => row.workspace === label);
    if (mine.length === 0) return '';
    const runtime = mine.filter((row) => row.kind === 'runtime');
    const development = mine.filter((row) => row.kind === 'development');
    return [`### ${label}`, '', ...(runtime.length ? ['Runtime:', '', table(runtime), ''] : []), ...(development.length ? ['Development only:', '', table(development), ''] : [])].join('\n');
  }),
  '### The whole installed tree',
  '',
  `${tree.size} packages are installed in total (direct and transitive). Licences by count: ${[...counts.entries()].sort((a, b) => b[1] - a[1]).map(([license, count]) => `${license} ${count}`).join(', ')}.`,
  '',
  unusual.length === 0 ? 'Every installed package has a permissive licence (MIT, Apache-2.0, BSD, ISC and similar).' : `Packages whose licence is not one of the plain permissive ones (all of them are development tools or optional, none is shipped in the bundles; review them):\n\n${unusual.map(([name, license]) => `- \`${name}\`: ${license}`).join('\n')}`,
  '',
].join('\n');

if (process.argv.includes('--write')) {
  const path = join(root, 'docs/DEPENDENCIES.md');
  const text = readFileSync(path, 'utf8');
  const marker = '<!-- generated by scripts/licenses.mjs: do not edit below this line -->';
  const head = text.includes(marker) ? text.slice(0, text.indexOf(marker)) : `${text}\n`;
  writeFileSync(path, `${head}${marker}\n\n${output}`);
  console.log('wrote docs/DEPENDENCIES.md');
} else {
  console.log(output);
}
